apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: shabad-os
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: shabados/website:latest
          name: website
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: shabad-os
spec:
  selector:
    app: website
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-ingress
  namespace: shabad-os
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: shabados.com
    http:
      paths:
      - backend:
          serviceName: website-service
          servicePort: 80