version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      # Enable Docker environment
      - setup_remote_docker
      # Fetch the source code
      - checkout
      # Log in to Docker Hub
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      # Build the image, tagging it with SHA1 image tag
      - run: docker build -t shabados/website:${CIRCLE_SHA1} .
      # Push the image to Docker Hub
      - run: docker push shabados/website:${CIRCLE_SHA1}

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master